/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice.java.app;

import practice.java.binarytree.BinaryTree;

public class App {
    public static void main(String[] args) {
        BinaryTree.run();
    }
}
