/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("practice.java.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":binarytree"))
}

application {
    // Define the main class for the application.
    mainClass.set("practice.java.app.App")
}
